trigger:
- master

variables:
 - group: "dev-ecommerce-shared"
 - group: "dev-ecommerce"
 - name: vmImageName
   value: 'ubuntu-latest'
 - name: workingDirectory
   value: '$(System.DefaultWorkingDirectory)/Ecommerce.Functions'
 - name : buildConfiguration
   value: 'Release'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.0.3'
        includePreviewVersions: false
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration $(buildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(workingDirectory)/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: ecommerce-functions

- stage: Dev
  displayName: Deploy stage
  dependsOn: Build
  jobs:
    - template: Deploy/terraform-pipelines.yml
      parameters:
          environment: $(environment)
          location_short: $(location_short)
          vmImageName: $(vmImageName)
          resourceGroupName: '$(resourceGroupName)'
          storageAccountName: '$(storageAccountName)'
          containerName: '$(containerName)'
          workingDir: 'Deploy/terraform'
          tfstateKey: '$(tfstateKey)'
