trigger:
- main

variables:
 - group: "dev-ecommerce"
 - name: vmImageName
   value: 'ubuntu-latest'
 - name: workingDirectory
   value: '$(System.DefaultWorkingDirectory)/Ecommerce.Functions'
 - name : buildConfiguration
   value: 'Release'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(workingDirectory)/*.csproj
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
          
- stage: Dev
  displayName: Deploy stage
  dependsOn: Build
  jobs:
    - template: Deploy/terraform-pipelines.yml
      parameters:
          environment: dev
          vmImageName: $(vmImageName)
          resourceGroupName: '$(resourceGroupName)'
          storageAccountName: '$(storageAccountName)'
          containerName: '$(containerName)'
          workingDir: 'Deploy/terraform'
          tfstateKey: '$(tfstateKey)'
